### ISSUE TITLE
Timeset covered by thumb

### ISSUE THREAD

**Issue by HanSolo361** [a-dekker/cooktimer#1]
When editing a timer out of the main page with one hand, the time to be set is covered by the thumb.
Maybe the timeset fits better above the clock so you can better watch the result of your setting.

**Comment by a-dekker** [comment]
Looks like a good suggestion and easy to implement I guess.

**Comment by a-dekker** [comment]
Version 0.1.21 pushed to openrepos.net; code on github updated

**Comment by HanSolo361** [comment]
too fast - too furios =D
Thx for the quick update!!
