### ISSUE TITLE
App for Jolla Tablet

### ISSUE THREAD

**Issue by carmenfdezb** [a-dekker/cooktimer#2]
Could you make this app for Jolla Tablet?

**Comment by a-dekker** [comment]
I think it will still have some scaling issues, but I will upload a version to openrepos.

**Comment by a-dekker** [comment]
Uploaded i486 build to openrepos.net. Can't test it at the moment.

**Comment by carmenfdezb** [comment]
I can test it if you want.
Thank you so much!!

**Comment by carmenfdezb** [comment]
It's working fine, thanks!!
There is an only scaling issue in 'Edit dishes' pages, here uou have a screenshot:
![screenshot-16-03-13-12-19-56](https://cloud.githubusercontent.com/assets/6286776/13728402/34f564d4-e917-11e5-82e7-63555e385fd4.png)

**Comment by a-dekker** [comment]
Thanks for reporting. I suspect the time picker circles are also a bit small.
I intent to have a closer look at this as soon as I have a tablet to test with.

**Comment by a-dekker** [comment]
Uploaded version 0.0.2-0 to openrepos.net, optimized for the tablet.

**Comment by carmenfdezb** [comment]
Great!! Thank you!!
