### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by JSEHV** [a-dekker/cooktimer#3]
I'd like to suggest an icon that fits well in the Sailfish OS design style, plus reflects the core of your app, timing cooking, which in the past was known as an 'egg timer'.

Colorwise it also pops more, so your app will have a better visual location on peoples phones. Hope you appreciate the effort.

![harbour-cooktimer-172x172](https://user-images.githubusercontent.com/5128988/50172868-4b4c1b00-02f6-11e9-8b82-9b2f2ca981e3.png)

All sizes:

[harbour-cooktimer.zip](https://github.com/a-dekker/cooktimer/files/2691673/harbour-cooktimer.zip)

**Comment by a-dekker** [comment]
Nice, I will use them in a next release!
